### Login oikealla salasanalla
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "username": "testi",
  "password": "testi"
}

### Login väärällä salasanalla
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "username": "juha",
  "password": "salasana-väärä"
}

### Post login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "username": "JohnDoe",
  "password": "to-be-hashed-pw1"
}

### Get my user info
GET http://localhost:3000/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1NCwibmFtZSI6InRlc3RpIiwidXNlcm5hbWUiOiJ0ZXN0aSIsImVtYWlsIjoidGVzdGlAZXhhbXBsZS5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDU0MjU1MiwiZXhwIjoxNzQ0NjI4OTUyfQ.34PIRO22H_295-gs3RCg9Zg94pnTe83sO_tubfyYBLM
