### Hae kaikki käyttäjät
GET http://localhost:3000/api/v1/users
Content-Type: application/json

### Hae yksittäinen
GET http://localhost:3000/api/v1/users/1
Content-Type: application/json

### käyttäjän luonti
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "name": "test",
  "username": "test",
  "password": "test",
  "email": "test@example.com"
}

### loggaaminen
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

### Poista käyttäjä, vain admin roolilla atm TODO: että käyttäjät voivat poistaa omansa
DELETE http://localhost:3000/api/v1/users/83
Content-Type: application/json
Authorization: Bearer <token>
